[project]
authors = ["Matthew Feickert <matthew.feickert@cern.ch>"]
channels = ["conda-forge"]
name = "talk-reinterpretation-forum-workshop-2025"
platforms = ["linux-64", "osx-64", "osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
cxx-compiler = ">=1.9.0,<2"
fortran-compiler = ">=1.9.0,<2"
lhapdf = ">=6.5.5,<7"
pythia8 = ">=8.312,<9"
smodels = ">=2.3.3,<3"
